version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Quasar
          command: 'sudo npm install -g @quasar/cli'
      - run:
          name: Install NPM packages
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Unit Tests
          command: 'quasar test --unit jest'
      - store_artifacts:
          path: ./test/jest/coverage
          prefix: test-results/jest
      - store_test_results:
          path: test-results

workflows:
  version: 2
  run-tests:
    jobs:
      - setup
      - test:
         requires:
          - setup
